Taco_Project/config/routes.rb
Rails.application.routes.draw do
  # resources :coupons
  # resources :categories
  # resources :ingredients
  resources :tacos
  resources :locations
  resources :users, only: [:show, :edit, :update, :new, :create]
  resources :orders, only: [:index]

  # APPLICATION CONTROLLER
  get '/about', to: 'application#about'
    get '/', to: 'application#index'

  # SESSIONS CONTROLLER
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # ORDERS CONTROLLER
  get '/finalize', to: 'orders#finalize'
  get '/finalized', to: 'orders#finalized'
  post '/add_signature', to: 'orders#add_signature'

  # TACOS CONTROLLER
  get '/delete_taco', to: 'tacos#destroy'
  get '/analytics', to: 'tacos#analytics'

  # ERRORS

  get '404', to: 'errors#notfound'

  patch '/remove_taco', to: 'users#remove_taco'

end

Taco_Project/app/models/taco.rb
class Taco < ApplicationRecord

  has_many :taco_ingredients
  has_many :user_tacos
  has_many :ingredients, through: :taco_ingredients
  has_many :users, through: :user_tacos

  # CLASS METHODS

  def self.most_popular(category)
    array = all.map{|taco| taco.item_name(category)}
    array.delete_if(&:blank?).max_by{|ingredient| array.count(ingredient)}
  end

  def self.average_calories
    all.map{|taco| taco.calories}.delete_if(&:blank?).reduce(:+) / all.length.to_f
  end

  def self.signature_tacos
    all.select{|taco| taco.signature == true}
  end

  # INSTANCE METHODS

  def calories
    self.ingredients.map{|i| i.calories}.reduce(:+) || 0
  end

  def generate_name
    if self.signature == true
      self.name
    else
      string = ""
      if self.has?("sauce")
        string = string + "#{item_name("sauces")} "
      end
      if self.has?("protein")
        string = string + "#{item_name("protein")} "
      end
      string = string + "Taco"
      if self.has?("topping")
        string = string + " with #{item_name("toppings")}"
      end
      string
    end
  end

  def has?(category)
    !ingredients.select{|ingredient| ingredient.category_name == category}.empty?
  end

  def taco_price
    total = 1
      self.ingredients.each do |ingredient|
        total += ingredient.price
      end
    total
  end

  # CUSTOM SETTER AND GETTER METHODS

  def protein
    self.ingredients.select do |ingredient|
      ingredient.category_name == "protein"
    end
  end

  def protein=(id)
    self.ingredients << Ingredient.find(id)
  end

  def bean
    self.ingredients.select do |ingredient|
      ingredient.category_name == "bean"
    end
  end

  def bean=(id)
    self.ingredients << Ingredient.find(id)
  end

  def tortilla
    self.ingredients.select do |ingredient|
      ingredient.category_name == "tortilla"
    end
  end

  def tortilla=(id)
    self.ingredients << Ingredient.find(id)
  end

  def rice
    self.ingredients.select do |ingredient|
      ingredient.category_name == "rice"
    end
  end

  def rice=(id)
    self.ingredients << Ingredient.find(id)
  end

  def sauces
    self.ingredients.select do |ingredient|
      ingredient.category.name == "sauce"
    end
  end

  def sauces=(array_of_ids)
    array_of_ids.reject(&:blank?).each do |id|
      self.ingredients << Ingredient.find(id)
    end
  end

  def toppings
    self.ingredients.select do |ingredient|
      ingredient.category_name == "topping"
    end
  end

  def toppings=(array_of_ids)
    array_of_ids.reject(&:blank?).each do |id|
      self.ingredients << Ingredient.find(id)
    end
  end

  def item_name(ingredient_type)
    if !self.send(ingredient_type.to_sym)[0].nil?
      self.send(ingredient_type.to_sym)[0].name.capitalize
    else
      ""
    end
  end

end

Taco_Project/app/controllers/tacos_controller.rb
class TacosController < ApplicationController

  before_action(:find_taco, only: [:show, :edit, :update, :destroy])
  before_action(:require_login)

  def new
    @user = current_user
    @taco = Taco.new
    @category = Category.all
    @extras = Ingredient.extra_cost
  end

  def create
    @user = current_user
    @taco = Taco.new(taco_params)
    if @taco.valid?
      @taco.save
      @user.tacos << @taco
      @user.save
      redirect_to orders_path
    else
      redirect_to :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @taco.update(taco_params)
    if @taco.valid?
      redirect_to @taco
    else
      redirect_to :edit
    end
  end

  def destroy
    @taco.destroy
    redirect_to orders_path
  end

  def analytics
    @tacos = Taco.all
  end

  private

  def find_taco
    @taco = Taco.find(params[:id])
  end

  def taco_params
    params.require(:taco).permit(
      :tortilla,
      :bean,
      :protein,
      :rice,
      sauces:[],
      toppings:[]
    )
  end

end

Taco_Project/app/helpers/tacos_helper.rb
module TacosHelper
end

Taco_Project/app/views/tacos/_form.html.erb
<%=form_for @taco do |f|%>
  <%=f.label "Choose Your Tortilla" %> <br>
  <%=f.collection_select(:tortilla, Ingredient.category("tortilla"), :id, :name)%><br>

  <%=f.label "Choose Your Rice" %> <br>
  <%=f.collection_select(:rice, Ingredient.category("rice"), :id, :name)%><br>

  <%=f.label "Choose Your Beans" %><br>
  <%=f.collection_select(:bean, Ingredient.category("bean"), :id, :name)%><br>

  <%=f.label "Choose Your Protein" %><br>
  <%=f.collection_select(:protein, Ingredient.category("protein"), :id, :name)%> <br>

  <%=f.label "Choose Your Toppings" %><br>
  <%=f.collection_check_boxes(:toppings,Ingredient.category("topping"), :id, :name)%><br>

  <%=f.label "Choose Your Sauce" %><br>
  <%=f.collection_check_boxes(:sauces, Ingredient.category("sauce"), :id, :name)%><br>

  <%=f.submit%>
<% end  %>

Taco_Project/app/views/tacos/_signature.html.erb
<div class="col-2 text-center signature_foods">
<%  if signature.name == "The John Cena" %>
  <a href="#" id="https://www.youtube.com/watch?v=9EPL_4HyCFQ" onclick="document.location=this.id;return false;" >
      <%= image_tag signature.img, :size => "198x198" %>
</a>
  <%else%>
<p><%= image_tag signature.img, :size => "198x198" %></p>
<%end%>
<p><%= signature.name %></p>
<p>Calories: <%= signature.calories %></p>
<p><%= signature.description %></p>
<p>
  <%= form_tag("/add_signature", method: :post) do%>
    <%= hidden_field_tag(name="signature_id", value=signature.id)%>
    <%= submit_tag("ADD TO ORDER")%>
  <% end %>
</p>
<br>
</div>

Taco_Project/app/views/tacos/analytics.html.erb
<style>


</style>


<div class="container">
  <h1>Taco Analytics</h1>

  <p>The cats have served <%=@tacos.length%> tacos to this day!</p>
  <p>The average taco has <%=Taco.average_calories%> calories.</p>

  <ul>
    <li>The most popular protein is: <%=Taco.most_popular("protein")%></li><br>
    <li>The most popular topping is: <%=Taco.most_popular("toppings")%></li><br>
    <li>The most popular rice is: <%=Taco.most_popular("rice")%></li><br>
    <li>The most popular sauce is: <%=Taco.most_popular("sauces")%></li><br>
  </ul>
</div>

Taco_Project/app/views/tacos/edit.html.erb
<div class="container">

  <!-- Row 1 -->

  <div class="row">
    <div class="col-1">
    </div>
    <div class="col-11 text-center">
      <h1>Edit Your Perfect Taco </h1>
    </div>
  </div>

  <!-- Row 2 -->

  <div class="row">
    <div class="col-12">
      <br>
    </div>
  </div>

  <!-- Row 3 -->

  <div class="row">

    <div class="col-1">

    </div>

    <div class="col-11">
        <%= render partial: 'form', locals: {taco: @taco} %>
    </div>


  </div>

</div>

Taco_Project/app/views/tacos/index.html.erb
<h1>Your Current Order</h1>

Taco_Project/app/views/tacos/new.html.erb
<div class="container">

  <!-- row 1 -->
  <div class="row">
    <div class="col-1">
    </div>
    <div class="col-11 text-center">
      <h1>Make Your Perfect Taco </h1>
    </div>
  </div>

  <!-- row 2 -->
  <div class="row">
    <div class="col-12">
      <br>
    </div>
  </div>

  <!-- row 3 -->

  <div class="row">
    <div class="col-7">
      <h2>Pick Your Ingredients</h2>
      <br>
      <%= render partial: 'form', locals: {taco: @taco} %>
    </div>

    <div class="col-5">
      <h2>WARNING!</h2>
      <br>
      <h3>The following ingredients cost extra</h3>
      <% @extras.each do |ingredient| %>
        <li><%= ingredient.name %> - <%= ingredient.price_string %> </li><br>
      <% end %>
      <%=image_tag "avocado_dabbing.jpg", size: '200' %>

    </div>

  </div>



</div>

Taco_Project/app/views/tacos/show.html.erb
<h1>Nice Taco!</h1>

<h2>Your Taco's Ingredients</h2>

<% @taco.ingredients.each do |ingredient| %>
  <ul>
    <%= ingredient.name %>
  </ul>
<% end %>

<h3><%=link_to "Edit This Taco", edit_taco_path(@taco)%></h3>
<h3><%= link_to "Make a new taco", new_taco_path %></h3>
<td><%= link_to 'Delete this Taco', taco_path(@taco),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
</tr>

<h3>Complete Your Order</h3>
<h3>Total Order Cost:</h3>