Taco_Project/config/routes.rb
Rails.application.routes.draw do
  # resources :coupons
  # resources :categories
  # resources :ingredients
  resources :tacos
  resources :locations
  resources :users, only: [:show, :edit, :update, :new, :create]
  resources :orders, only: [:index]

  # APPLICATION CONTROLLER
  get '/about', to: 'application#about'
    get '/', to: 'application#index'

  # SESSIONS CONTROLLER
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # ORDERS CONTROLLER
  get '/finalize', to: 'orders#finalize'
  get '/finalized', to: 'orders#finalized'
  post '/add_signature', to: 'orders#add_signature'

  # TACOS CONTROLLER
  get '/delete_taco', to: 'tacos#destroy'
  get '/analytics', to: 'tacos#analytics'

  # ERRORS

  get '404', to: 'errors#notfound'

  patch '/remove_taco', to: 'users#remove_taco'

end

Taco_Project/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action(:find_user, only: [:index, :finalize, :finalized, :add_signature])
  before_action(:require_login)

  def index
    @signatures = Taco.signature_tacos
  end

  def finalize
  end

  def finalized
    ApplicationMailer.receipt_email(@user).deliver_now
    @user.deactivate_tacos
    @user.save
  end

  def add_signature
    @user.tacos << Taco.find(params[:signature_id])
    redirect_to '/orders'
  end

  private

  def find_user
    @user = current_user
  end

end

Taco_Project/app/views/orders/finalize.html.erb
<div class="container">

  <h1>Your Current Order </h1>
  <ul>
  <% @user.active_tacos.each_with_index do |taco, index|%>
    <% indexplusone = index + 1 %>
    <li><%= taco.generate_name %> |</li>
    <li>Price: $<%= taco.taco_price %> </li><br>
  <% end %>
  </ul>
  <h3>Total Order Cost: $<%=@user.total %></h3>

  <h3><%=link_to "Go Back & Edit Your Order", '/orders'%></h3>

  <h2><%=link_to "Finalize Order", finalized_path%></h2>

</div>

Taco_Project/app/views/orders/finalized.html.erb
<div class="container">

<h1>Thank you for your order!</h1>

<h3>You will receive an e-mail with your receipt.</h3>

</div>

Taco_Project/app/views/orders/index.html.erb
<style media="screen">
  input[type="submit"] {
    border-style: none;
    color: #167AF6;
  }
  .wrapper {
    display: flex;
    width: 100%;
  }

  #sidebarorder {
    width: 250px;
    position: fixed;
    top: 0;
    right: 0;
    height: 100vh;
    z-index: 1;
    background: #fff;
    color: #000;
    transition: all 0.3s;
  }
  .sidebar-header{
    margin-bottom: 100px;
  }
  #navtitle {
    margin-top: 50px;
    margin-bottom: -5px;
    z-index: 2;
  }
.owntaco{
  margin-top: 30px;
}
.revieworder{
  position: absolute;
  margin-top: 200px;
}

html h3 {
    font-size: 20px !important;
}

</style>

<div class="container">
  <!-- row 1 -->
  <div class="row">
    <div class="col-1">
    </div>
    <div class="col-11 text-center">
      <h3>Our Signature Tacos</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <br>
    </div>
  <!-- row 2 -->
  <!-- 5 signature tacos -->
  <div class="row">
    <div class="col-1">

    </div>
          <p class="signature-taco">
      <%= render partial: 'tacos/signature', collection: @signatures %><br>
    </p>
</a>
</div>
    <div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebarorder">
            <div class="sidebar-header">
              <h1 class ="title" id="navtitle" class="indexcat">Your Order:</h1>
                <div class="navbarbootstrap">
                    <div class="row">
                      <div class="col-12 owntaco">
                        <h2><%= link_to "Make Your Own 🌮", new_taco_path %></h2>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-12">
                        <% @user.active_tacos.each do |taco| %>

                          <h3><%= taco.generate_name %> - $<%= taco.taco_price %> - (<%=link_to("EDIT", edit_taco_path(taco))%>,
                            <%=form_for @user, url: '/remove_taco' do |f|%>
                              <%= f.hidden_field :taco_id, value: taco.id %>
                              <%= f.submit "DELETE" %>)
                            <% end %>
                          </h3>

                        <% end %>
                      </div>
                    </div>
                    <div class="row">
                        <div class="col-12 revieworder">
                          <h3><%=link_to "Review Your Order", finalize_path(@user) %></h3>
                          <h3>Total Order Cost: $<%=@user.total %></h3>
                        </div>
                    </div>
                  </div>
                </div>
              </nav>
        </div>
    </div>



</div>